### ISSUE TITLE
`@prisma/client`dependency is required for check-for-dev-update job

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#1625]
Create a test without Prisma Client, like for the Studio test will result in 

Example https://github.com/prisma/e2e-tests/runs/2352622269?check_suite_focus=true

Missing client dependency in package.json
```
{
  "name": "studio",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "test": "jest"
  },
  "devDependencies": {
    "@types/jest": "26.0.22",
    "@types/node": "14.14.39",
    "@types/node-fetch": "2.5.10",
    "jest": "26.6.3",
    "node-fetch": "2.6.1",
    "prisma": "2.22.0-dev.7",
    "ts-jest": "26.5.4",
    "typescript": "4.2.4"
  }
}
```

Results in
```
....
var pkg=require('./package.json'); if (pkg.workspaces || pkg.name == '.prisma/client' || pkg.name == 'web') { process.exit(0); };console.log(pkg.dependencies['@prisma/client'])
                                                                                                                                                             ^
TypeError: Cannot read property '@prisma/client' of undefined
    at [eval]:1:158
    at Script.runInThisContext (vm.js:120:18)
    at Object.runInThisContext (vm.js:309:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
Error: Process completed with exit code 1.
```

**Comment by Jolg42** [comment]
line mentioned in log
https://github.com/prisma/e2e-tests/blob/1a4dbad34db467569ae2caf138c5efc9a3a9c576/.github/scripts/check-for-update.sh#L50

**Comment by millsp** [comment]
Fixed in the new pnpm setup.
