### ISSUE TITLE
vercel-with-redwood: "TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null"

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1683]
https://github.com/prisma/e2e-tests/runs/2501176972?check_suite_focus=true

Something weird is happening here:

```
finally script found, executing platforms-serverless/vercel-with-redwood/finally.sh

yarn run v1.22.10
$ /home/runner/work/e2e-tests/e2e-tests/platforms-serverless/vercel-with-redwood/node_modules/.bin/vercel logs e2e-vercel-with-redwood.vercel.app --token=*** --scope=prisma
Vercel CLI 22.0.1
- Fetching deployment "e2e-vercel-with-redwood.vercel.app" in prisma
> Fetched deployment "e2e-vercel-with-redwood-oalb6nyr7-prisma.vercel.app" in prisma [439ms]
2021-05-04T14:20:35.327Z  Generating the Prisma client... [completed]
2021-05-04T14:20:35.364Z  [14:20:35] Cleaning "web"... (./web/dist/) [started]
2021-05-04T14:20:35.470Z  [14:20:35] Cleaning "web"... (./web/dist/) [completed]
2021-05-04T14:20:35.470Z  [14:20:35] Building "api"... [started]
2021-05-04T14:20:40.110Z  [14:20:40] Building "api"... [completed]
2021-05-04T14:20:40.111Z  [14:20:40] Building "web"... [started]
2021-05-04T14:20:41.819Z  [14:20:41] Building "web"... [failed]
2021-05-04T14:20:41.819Z  [14:20:41] → Command failed with exit code 1: yarn cross-env NODE_ENV=production webpack --config ../node_modules/@redwoodjs/core/config/webpack.production.js
2021-05-04T14:20:41.820Z  /vercel/path1/node_modules/webpack-cli/bin/cli.js:93
2021-05-04T14:20:41.820Z  				throw err;
2021-05-04T14:20:41.820Z  				^
2021-05-04T14:20:41.820Z  
2021-05-04T14:20:41.820Z  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
2021-05-04T14:20:41.820Z      at validateString (internal/validators.js:124:11)
2021-05-04T14:20:41.820Z      at Object.resolve (path.js:980:7)
2021-05-04T14:20:41.820Z      at module.exports (/vercel/path1/node_modules/@redwoodjs/core/config/webpack.common.js:194:35)
2021-05-04T14:20:41.820Z      at Object.<anonymous> (/vercel/path1/node_modules/@redwoodjs/core/config/webpack.production.js:3:20)
2021-05-04T14:20:41.820Z      at Module._compile (/vercel/path1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
2021-05-04T14:20:41.820Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.820Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.820Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.820Z      at Module.require (internal/modules/cjs/loader.js:952:19)
2021-05-04T14:20:41.821Z      at require (/vercel/path1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
2021-05-04T14:20:41.822Z      at WEBPACK_OPTIONS (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
2021-05-04T14:20:41.822Z      at requireConfig (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
2021-05-04T14:20:41.822Z      at /vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
2021-05-04T14:20:41.822Z      at Array.forEach (<anonymous>)
2021-05-04T14:20:41.822Z      at module.exports (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
2021-05-04T14:20:41.823Z      at /vercel/path1/node_modules/webpack-cli/bin/cli.js:71:45
2021-05-04T14:20:41.823Z      at Object.parse (/vercel/path1/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
2021-05-04T14:20:41.823Z      at /vercel/path1/node_modules/webpack-cli/bin/cli.js:49:8
2021-05-04T14:20:41.823Z      at Object.<anonymous> (/vercel/path1/node_modules/webpack-cli/bin/cli.js:366:3)
2021-05-04T14:20:41.823Z      at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-05-04T14:20:41.823Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.823Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.823Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.823Z      at Module.require (internal/modules/cjs/loader.js:952:19)
2021-05-04T14:20:41.823Z      at require (internal/modules/cjs/helpers.js:88:18)
2021-05-04T14:20:41.823Z      at Object.<anonymous> (/vercel/path1/node_modules/@storybook/builder-webpack4/node_modules/webpack/bin/webpack.js:156:2)
2021-05-04T14:20:41.823Z      at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-05-04T14:20:41.823Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.824Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.824Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.824Z      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2021-05-04T14:20:41.824Z      at internal/main/run_main_module.js:17:47 ***
2021-05-04T14:20:41.824Z    code: 'ERR_INVALID_ARG_TYPE'
2021-05-04T14:20:41.824Z  ***
2021-05-04T14:20:41.824Z  error Command failed with exit code 1.
2021-05-04T14:20:41.824Z  $ /vercel/path1/node_modules/.bin/cross-env NODE_ENV=production webpack --config ../node_modules/@redwoodjs/core/config/webpack.production.js
2021-05-04T14:20:41.824Z  info Visit yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T14:20:41.824Z  Command failed with exit code 1: yarn cross-env NODE_ENV=production webpack --config ../node_modules/@redwoodjs/core/config/webpack.production.js
2021-05-04T14:20:41.824Z  /vercel/path1/node_modules/webpack-cli/bin/cli.js:93
2021-05-04T14:20:41.825Z  				throw err;
2021-05-04T14:20:41.825Z  				^
2021-05-04T14:20:41.825Z  
2021-05-04T14:20:41.825Z  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
2021-05-04T14:20:41.825Z      at validateString (internal/validators.js:124:11)
2021-05-04T14:20:41.825Z      at Object.resolve (path.js:980:7)
2021-05-04T14:20:41.825Z      at module.exports (/vercel/path1/node_modules/@redwoodjs/core/config/webpack.common.js:194:35)
2021-05-04T14:20:41.825Z      at Object.<anonymous> (/vercel/path1/node_modules/@redwoodjs/core/config/webpack.production.js:3:20)
2021-05-04T14:20:41.825Z      at Module._compile (/vercel/path1/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
2021-05-04T14:20:41.825Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.825Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.825Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.826Z      at Module.require (internal/modules/cjs/loader.js:952:19)
2021-05-04T14:20:41.826Z      at require (/vercel/path1/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
2021-05-04T14:20:41.826Z      at WEBPACK_OPTIONS (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
2021-05-04T14:20:41.826Z      at requireConfig (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
2021-05-04T14:20:41.826Z      at /vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
2021-05-04T14:20:41.826Z      at Array.forEach (<anonymous>)
2021-05-04T14:20:41.826Z      at module.exports (/vercel/path1/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
2021-05-04T14:20:41.826Z      at /vercel/path1/node_modules/webpack-cli/bin/cli.js:71:45
2021-05-04T14:20:41.826Z      at Object.parse (/vercel/path1/node_modules/webpack-cli/node_modules/yargs/yargs.js:576:18)
2021-05-04T14:20:41.826Z      at /vercel/path1/node_modules/webpack-cli/bin/cli.js:49:8
2021-05-04T14:20:41.826Z      at Object.<anonymous> (/vercel/path1/node_modules/webpack-cli/bin/cli.js:366:3)
2021-05-04T14:20:41.826Z      at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-05-04T14:20:41.826Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.827Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.827Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.827Z      at Module.require (internal/modules/cjs/loader.js:952:19)
2021-05-04T14:20:41.827Z      at require (internal/modules/cjs/helpers.js:88:18)
2021-05-04T14:20:41.827Z      at Object.<anonymous> (/vercel/path1/node_modules/@storybook/builder-webpack4/node_modules/webpack/bin/webpack.js:156:2)
2021-05-04T14:20:41.827Z      at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-05-04T14:20:41.827Z      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-05-04T14:20:41.827Z      at Module.load (internal/modules/cjs/loader.js:928:32)
2021-05-04T14:20:41.827Z      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-05-04T14:20:41.827Z      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
2021-05-04T14:20:41.827Z      at internal/main/run_main_module.js:17:47 ***
2021-05-04T14:20:41.827Z    code: 'ERR_INVALID_ARG_TYPE'
2021-05-04T14:20:41.827Z  ***
2021-05-04T14:20:41.827Z  error Command failed with exit code 1.
2021-05-04T14:20:41.828Z  $ /vercel/path1/node_modules/.bin/cross-env NODE_ENV=production webpack --config ../node_modules/@redwoodjs/core/config/webpack.production.js
2021-05-04T14:20:41.828Z  info Visit yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T14:20:41.839Z  error Command failed with exit code 1.
2021-05-04T14:20:41.840Z  info Visit yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-05-04T14:20:41.863Z  Done in 14.55s.
2021-05-04T14:20:52.602Z  Uploading build outputs...
2021-05-04T14:20:53.748Z  Deploying build outputs...
2021-05-04T14:20:59.940Z  
2021-05-04T14:21:02.940Z  Build completed. Populating build cache...
Done in 2.27s.

finished finally.sh
```

**Comment by janpio** [comment]
Fixed now
