### ISSUE TITLE
Understand uncaught promise failure on generic/basic node tests

### ISSUE THREAD

**Issue by janpio** [prisma/ecosystem-tests#1750]
Super weird, the test is not failing while the script inside is definitely not succeeding fully:

```
(node:1938) UnhandledPromiseRejectionWarning: Error [InvalidArg]: 
    at connectPromise.Promise (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:23068:77)
    at new Promise (<anonymous>)
    at NAPIEngine.start (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:23065:31)
(node:1938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1938) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
https://github.com/prisma/e2e-tests/pull/1749/checks?check_run_id=2752844993#step:5:98

Seems our test script is not sufficient here: https://github.com/prisma/e2e-tests/blob/dev/generic/basic/script.ts

---

Same is happening for node 12.2.0:
```
yarn run v1.22.10
warning ../../package.json: No license field
$ ts-node ./script.ts
(node:2105) UnhandledPromiseRejectionWarning: Error: 
    at /home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:23068:77
    at new Promise (<anonymous>)
    at NAPIEngine.start (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:23065:31)
    at NAPIEngine.request (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:23135:9)
    at cb (/home/runner/work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/client/runtime/index.js:34158:26)
(node:2105) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2105) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 1.54s.
```
https://github.com/prisma/e2e-tests/pull/1749/checks?check_run_id=2752845004#step:5:102

**Comment by janpio** [comment]
Here is another example, where it definitely fails and did not work, but the script does not fail:

```
...
  prisma:getConfig Using N-API Query Engine at: /Users/administrator/actions-runner/_work/e2e-tests/e2e-tests/generic/basic/node_modules/@prisma/engines/libquery_engine_napi-darwin.dylib.node +777ms
✨  Done in 2.61s.
-----------------------------

run.sh was successful (code 0), running generic/basic/test.sh...

yarn run v1.22.10
warning ../../package.json: No license field
$ ts-node ./script.ts
(node:95268) UnhandledPromiseRejectionWarning: Error: {"is_panic":false,"message":"Can't reach database server at `foo`:`5432`\n\nPlease make sure your database server is running at `foo`:`5432`.","meta":{"database_host":"foo","database_port":5432},"error_code":"P1001"}
(node:95268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:95268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 4.07s.

finished test.sh (code 0)

-----------------------------
-------------- Checking Binaries ---------------
-------------- Checking CLI/Engines QE Binary --------------
...
```

**Comment by janpio** [comment]
related: https://github.com/prisma/prisma/issues/7621

**Comment by janpio** [comment]
Will be avoided via https://github.com/prisma/prisma/issues/8839
