### ISSUE TITLE
Update dependency prisma-nestjs-graphql to v15

### ISSUE THREAD

**Issue by Jolg42** [prisma/ecosystem-tests#2662]
New version is currently failing with

https://github.com/prisma/ecosystem-tests/runs/5976145513?check_suite_focus=true#step:6:316
```
$ jest
FAIL ./index.test.js
  test generator
    ✕ should produce same prisma ts file for same Prisma schema (5 ms)
    ✕ should produce same user ts file for same Prisma schema (1 ms)

  ● test generator › should produce same prisma ts file for same Prisma schema

    expect(received).toMatchSnapshot()

    Snapshot name: `test generator should produce same prisma ts file for same Prisma schema 1`

    - Snapshot  - 0
    + Received  + 1

    @@ -2,9 +2,10 @@
      import { ObjectType } from '@nestjs/graphql';
      import { Int } from '@nestjs/graphql';

      @ObjectType()
      export class AffectedRows {
    +
          @Field(() => Int, {nullable:false})
          count!: number;
      }
      ↵

       6 |       encoding: 'utf8',
       7 |     })
    >  8 |     expect(content).toMatchSnapshot()
         |                     ^
       9 |   })
      10 |
      11 |   it('should produce same user ts file for same Prisma schema', () => {

      at Object.<anonymous> (index.test.js:8:21)

  ● test generator › should produce same user ts file for same Prisma schema

    ENOENT: no such file or directory, open './prisma-nestjs-graphql/user/aggregate-user.args.ts'

      10 |
      11 |   it('should produce same user ts file for same Prisma schema', () => {
    > 12 |     const content = fs.readFileSync('./prisma-nestjs-graphql/user/aggregate-user.args.ts', {
         |                        ^
      13 |       encoding: 'utf8',
      14 |     })
      15 |     expect(content).toMatchSnapshot()

      at Object.<anonymous> (index.test.js:12:24)

 › 1 snapshot failed.
```

_Originally posted by @Jolg42 in https://github.com/prisma/ecosystem-tests/issues/2564#issuecomment-1096309063_

**Comment by Jolg42** [comment]
Current version is `"prisma-nestjs-graphql": "17.0.1"` and passing
